/**
 * Generated by the Croct CLI.
 *
 * Any manual changes will be overwritten.
 *
 * To regenerate, run `croct update`.
 */

/**
 * Coupon list
 * 
 * A list of coupons.
 */
type Def$06121f1f = {
  /**
   * Coupons
   */
  'coupons': Array<{
    /**
     * Code
     * 
     * The coupon code.
     */
    'code': string,
    /**
     * Rule
     * 
     * The eligibility condition for the coupon.
     */
    'rule': string,
    /**
     * Title
     * 
     * Display name shown after the coupon is applied.
     */
    'title': string,
    /**
     * Discount
     * 
     * Percentage discount from 0% to 100%.
     */
    'discount'?: number,
    /**
     * Eligible
     * 
     * Whether the current user is eligible for this coupon.
     */
    'eligible': boolean,
    /**
     * Max discount
     * 
     * Maximum discount as an absolute monetary value. Omit for no cap
     */
    'maxDiscount'?: number,
    /**
     * Free shipping
     * 
     * Whether the coupon waives the shipping fee.
     */
    'freeShipping': boolean,
  }>,
};

type Def$b1ebca0b = {
  /**
   * cta
   */
  'cta'?: Array<Def$d7e290d5>,
  /**
   * text
   */
  'text': string,
};

/**
 * CTA
 */
type Def$d7e290d5 = {
  /**
   * link
   */
  'link': string,
  /**
   * label
   */
  'label': string,
};

type Def$f366e9fc = {
  /**
   * icon
   */
  'icon': Def$0147aaec,
  /**
   * text
   */
  'text': string,
  /**
   * title
   */
  'title': string,
};

type Def$0147aaec = string;

type Def$110e4751 = {
  /**
   * cta
   */
  'cta': Array<Def$d7e290d5>,
  /**
   * image
   */
  'image': Def$0147aaec,
  /**
   * tagline
   */
  'tagline'?: string,
  /**
   * headline
   */
  'headline': string,
};

declare module '@croct/plug/slot' {
  type CouponsV3 = Def$06121f1f & {'_component': 'coupon-list@3' | null};
  type SiteWideTopBarV3 = Def$b1ebca0b & {'_component': 'announcement-bar@3' | null};
  type CheckoutCalloutV2 = Def$f366e9fc & {'_component': 'checkout-callout@1' | null};
  type HomeHeroV2 = Def$110e4751 & {'_component': 'hero-section@2' | null};
  
  export interface VersionedSlotMap {
    'coupons': {
      latest: CouponsV3,
      '3': CouponsV3,
    };

    'site-wide-top-bar': {
      latest: SiteWideTopBarV3,
      '3': SiteWideTopBarV3,
    };

    'checkout-callout': {
      latest: CheckoutCalloutV2,
      '2': CheckoutCalloutV2,
    };

    'home-hero': {
      latest: HomeHeroV2,
      '2': HomeHeroV2,
    };
  }
}

export {};